Trix.config.lang =
  bold: "加粗"
  bullets: "Bullets"
  byte:  "Byte"
  bytes: "Bytes"
  captionPlaceholder: "添加图片说明文字..."
  code: "代码"
  heading1: "一级标题"
  indent: "Increase Level"
  italic: "Italic"
  link: "链接"
  numbers: "Numbers"
  outdent: "Decrease Level"
  quote: "引用"
  redo: "重做"
  remove: "删除"
  strike: "Strikethrough"
  undo: "恢复"
  unlink: "取消链接"
  url: "URL"
  urlPlaceholder: "请输入网址..."
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"
